repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: check-json
    -   id: pretty-format-json
        args: ['--autofix', '--no-sort-keys']
-   repo: https://github.com/ambv/black
    rev: 21.9b0
    hooks:
    - id: black
      language_version: python3.8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.910'
    hooks:
    -   id: mypy
        name: mypy
-   repo: https://github.com/pycqa/pydocstyle
    rev: '6.1.1'
    hooks:
    -   id: pydocstyle
-   repo: https://github.com/PyCQA/bandit
    rev: '1.7.0'
    hooks:
    - id: bandit
      args: [--skip, "B101,B303,B110"]
-   repo: https://gitlab.com/pycqa/flake8
    rev: '3.9.2'
    hooks:
    -   id: flake8
        args: ["--ignore=E203,E266,E501,W503,F403,F401,E402,C901", --max-line-length=88, --max-complexity=18, "--select=B,C,E,F,W,T4,B9"]
