name: FHIR Validation

on:
  push:
    branches:
      - main
      - master
      - staging
  pull_request:
    branches:
      - main
      - master
      - staging

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  CI_FHIR_VALIDATION:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: Execute validator
        run: |
          python validate_profile.py --all
